SET SERVEROUTPUT ON

DECLARE 
	TYPE m_TABL IS TABLE OF VARCHAR2(128)
	INDEX BY BINARY_INTEGER;
	
	MY_Tabl m_TABL;
	
	m_CNT BINARY_INTEGER;
	
	a BINARY_INTEGER;
	
BEGIN
	FOR i IN 1..100 LOOP
		MY_Tabl(i) := TO_CHAR(i + 5);
	END LOOP;
	
	DBMS_OUTPUT.ENABLE;
	
	m_CNT := MY_Tabl.FIRST;
	
	LOOP
		DBMS_OUTPUT.PUTLINE('Table is : ' || TO_CHAR(MY_Tabl(m_CNT)));
		EXIT WHEN m_CNT = MY_Tabl.LAST;
		m_CNT = MY_Tabl.NEXT(m_CNT);	
	END LOOP;
	
	m_CNT := MY_Tabl.LAST;
	
	LOOP 
		DBMS_OUTPUT.PUTLINE('Tabl is : ' || TO_CHAR(MY_Tabl(m_CNT)));
		EXIT WHEN m_CNT = MY_TABL.FIRST;
		m_CNT : = MY_Tabl.PRIOR(m_CNT);
	END LOOP;
END;
/