CREATE OR REPLACE TRIGGER TRIGGER_BEFORE_DEL 
BEFORE DELETE ON TOVAR_GROUP 
FOR EACH ROW 
DECLARE 
    CURSOR Curs_GET IS SELECT * FROM tovar WHERE id_group = :old.id_group;
BEGIN
    FOR i IN Curs_GET LOOP
        DELETE FROM TOVAR WHERE id_tovar = i.id_tovar;
    END LOOP;
END;